version: 2.1

orbs:
  slack: circleci/slack@4.3.0

executors:
  macos-executor:
    macos:
      xcode: 14.0.0

commands:
  setup:
    steps:
      - checkout
      - restore_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle --clean
      - save_cache:
          key: gems-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: for ip in $(dig @8.8.8.8 github.com +short); do ssh-keyscan github.com,$ip; ssh-keyscan $ip; done 2>/dev/null >> ~/.ssh/known_hosts
  setup_mapbox:
    steps:
      - run:
          command: |
            touch ~/.netrc
            chmod 600 ~/.netrc
            echo "machine api.mapbox.com login mapbox password $IOS_MAPBOX_DOWNLOAD_ACCESS_TOKEN" >> ~/.netrc
            [ ! -f "voice-guidance/Resources/Plists/Mapbox-Info.plist" ] && plutil -replace MGLMapboxAccessToken -string $IOS_MAPBOX_ACCESS_TOKEN voice-guidance/Resources/Plists/Mapbox-Example-Info.plist
            [ ! -f "voice-guidance/Resources/Plists/Mapbox-Info.plist" ] && cp voice-guidance/Resources/Plists/Mapbox-Example-Info.plist voice-guidance/Resources/Plists/Mapbox-Info.plist
  slack_notify_fail:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
  slack_notify_success:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  unit-tests:
    executor:
      name: macos-executor
    steps:
      - setup
      - setup_mapbox
      - run: bundle exec fastlane unit_tests
      - store_test_results:
          path: unit_test_output
      - store_artifacts:
          path: unit_test_output
          destination: scan-output
      - slack_notify_fail
  snapshot-tests-on-iphone12promax:
    executor:
      name: macos-executor
    steps:
      - setup
      - setup_mapbox
      - run: bundle exec fastlane snapshot_tests_on_iphone12promax
      - store_test_results:
          path: snapshot_test_output
      - store_artifacts:
          path: snapshot_test_output
          destination: scan-output
      - slack_notify_fail
  snapshot-tests-on-ipodtouch7thgeneration:
    executor:
      name: macos-executor
    steps:
      - setup
      - setup_mapbox
      - run: bundle exec fastlane snapshot_tests_on_ipodtouch7thgeneration
      - store_test_results:
          path: snapshot_test_output
      - store_artifacts:
          path: snapshot_test_output
          destination: scan-output
      - slack_notify_fail
  ui-tests:
    executor:
      name: macos-executor
    steps:
      - setup
      - setup_mapbox
      - run: bundle exec fastlane ui_tests
      - store_test_results:
          path: unit_test_output
      - store_artifacts:
          path: unit_test_output
          destination: scan-output
      - slack_notify_fail
  beta:
    executor:
      name: macos-executor
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5a:f3:28:71:8a:cf:89:7a:e8:f5:01:4a:8e:f2:a8:dc"
            - "8f:8e:c0:8b:65:0f:89:e3:be:73:33:f7:c6:86:af:e4"
      - setup
      - setup_mapbox
      - run: bundle exec fastlane beta_upload
      - slack_notify_fail
      - slack_notify_success

workflows:
  version: 2.1
  test-and-upload:
    jobs:
      - unit-tests:
          context: audio-tour
          filters:
            branches:
              only: main
      - snapshot-tests-on-iphone12promax:
          context: audio-tour
          filters:
            branches:
              only: main
      - snapshot-tests-on-ipodtouch7thgeneration:
          context: audio-tour
          filters:
            branches:
              only: main
#      - ui-tests:
#          context: audio-tour
#          filters:
#            branches:
#              only: main
      - beta:
          requires:
            - unit-tests
            - snapshot-tests-on-iphone12promax
            - snapshot-tests-on-ipodtouch7thgeneration
#            - ui-tests
          context: audio-tour
          filters:
            branches:
              only: main
