default_platform :ios

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Unit testing"
  lane :unit_tests do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "voice-guidance",
      device: "iPhone 8",
      only_testing: "voice-guidanceTests"
    )
  end

  desc "Snapshot testing on iPhone 14 Pro Max"
  lane :snapshot_tests_on_iphone14promax do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "voice-guidance",
      device: "iPhone 14 Pro Max",
      only_testing: "voice-guidanceSnapshotTests"
    )
  end

  desc "Snapshot testing on iPhone SE 3rd generation"
  lane :snapshot_tests_on_iphonese3rdgeneration do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "voice-guidance",
      device: "iPhone SE (3rd generation)",
      only_testing: "voice-guidanceSnapshotTests"
    )
  end

  desc "UI testing"
  lane :ui_tests do
    scan(
      include_simulator_logs: false,
      code_coverage: true,
      clean: true,
      scheme: "voice-guidance",
      device: "iPhone 8",
      only_testing: "voice-guidanceUITests"
    )
  end

  desc "Upload beta build"
  lane :beta_upload do
    increment_build_number(
      build_number: "#{ENV['CIRCLE_BUILD_NUM']}"
    )
    app_store_connect_api_key(
      key_id: "#{ENV['APP_STORE_CONNECT_KEY_ID']}",
      issuer_id: "#{ENV['APP_STORE_CONNECT_ISSUER_ID']}",
      key_content: "#{ENV['APP_STORE_CONNECT_KEY_CONTENT']}",
      duration: 1200,
      in_house: false,
    )
    match(type: "appstore", app_identifier: "org.kenzan8000.san-francisco")
    gym(export_method: "app-store", configuration: "san_francisco", scheme: "voice-guidance")
    pilot
  end
end
